#theme: jekyll-theme-midnight
theme: jekyll-theme-tactile

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      author: "Abby"
