theme: jekyll-theme-midnight
#theme: jekyll-theme-tactile

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

#  -
#    scope:
#      path: "projects"
#      type: "pages"
#    values:
#      layout: "project"
#      author: "Abby"

  -
    scope:
      path: "assets/images"
    values:
      image: true